from langchain.chains import RetrievalQA
from langchain_community.document_loaders import PyPDFLoader, TextLoader
from langchain_community.vectorstores import MongoDBAtlasVectorSearch
from langchain_openai import ChatOpenAI, OpenAI, OpenAIEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnablePassthrough, RunnableLambda
from langchain_core.output_parsers import StrOutputParser
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage # Already imported by you
from pymongo import MongoClient
from dotenv import load_dotenv

import os

load_dotenv()

def debug_prompt_output(prompt_value_object):
    """
    Debugs the PromptValue object generated by a LangChain prompt template within a chain.
    It prints the content of the prompt (as a string or list of messages).
    """
    print("\n--- DEBUG: Prompt Sent to LLM ---")
    
    # Check if it's a string prompt or a chat prompt
    if hasattr(prompt_value_object, "to_string"):
        # For simple string prompts
        print("Rendered Prompt (as string):\n", prompt_value_object.to_string())
    elif hasattr(prompt_value_object, "to_messages"):
        # For chat prompts (list of messages)
        print("Rendered Prompt (as messages):")
        for msg in prompt_value_object.to_messages():
            if isinstance(msg, SystemMessage):
                print(f"System Message: {msg.content}")
            elif isinstance(msg, HumanMessage):
                print(f"Human Message: {msg.content}")
            elif isinstance(msg, AIMessage):
                print(f"AI Message: {msg.content}")
            else:
                print(f"Other Message Type ({type(msg).__name__}): {str(msg)}")
    else:
        # Fallback for unexpected prompt value types
        print("Rendered Prompt (raw object):\n", prompt_value_object)
    
    print("--- END DEBUG ---\n")
    
    return prompt_value_object # IMPORTANT: Pass the object through to the next step

# This debug function is placed before the prompt template to see what's being passed as context
def debug_chain_input(input_dict):
    # input_dict will have 'context' and 'question'
    context_docs = input_dict["context"]
    question = input_dict["question"]

    full_context_text = "\n\n".join([doc.page_content for doc in context_docs])
    print("\n--- DEBUG: Retrieved Context ---")
    print(f"Number of documents retrieved: {len(context_docs)}")
    print(f"Total characters in retrieved context: {len(full_context_text)}")
    print(f"Question: {question}")
    print("--- END DEBUG ---\n")
    # Pass through the original input for the next step in the chain
    return input_dict

# Your main code starts here

model = ChatOpenAI(model="gpt-4-turbo-preview")
# Remove or comment out this line. You don't need llm if you're using 'model' (ChatOpenAI)
# llm = OpenAI() 

ATLAS_CONNECTION_STRING = os.getenv("ATLAS_CONNECTION_STRING")
DB_NAME = os.getenv("DB_NAME")
COLLECTION_NAME = os.getenv("COLLECTION_NAME")
ATLAS_VECTOR_SEARCH_INDEX_NAME = os.getenv("ATLAS_VECTOR_SEARCH_INDEX_NAME") # Fix: this might be a typo, should be ATLAS_VECTOR_SEARCH_INDEX_NAME

# Connect to your Atlas cluster
client = MongoClient(ATLAS_CONNECTION_STRING)

# Define collection and index name
collection = client[DB_NAME][COLLECTION_NAME]

if client:
    print("Connected to MongoDB Atlas")
    print(client.list_database_names())

# Load the sample data (PDF document)
loader = PyPDFLoader("imitacion_de_cristo.pdf")
data = loader.load()

# Split PDF into smaller documents
# Adjusted chunk_size for potentially larger documents if k=10 is used
# Although 200 is fine, ensure it's not too small if you want rich context
text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50) 
docs = text_splitter.split_documents(data)

# Print the first document
print(docs[0])

# Instantiate the vector store
vector_store = MongoDBAtlasVectorSearch.from_documents(
    documents=docs,
    embedding=OpenAIEmbeddings(disallowed_special=()),
    collection=collection, # Corrected in previous step
    index_name=ATLAS_VECTOR_SEARCH_INDEX_NAME # Fix: this might be a typo, should be ATLAS_VECTOR_SEARCH_INDEX_NAME
)

# ... (rest of your imports and setup)

# Instantiate Atlas Vector Search as a retriever
retriever = vector_store.as_retriever(
    search_type="similarity", search_kwargs={"k": 10}
)

# Define a prompt template
template = """
    Use the following pieces of context to answer the question at the end.
    If you don't know the answer, just say that you don't know, don't try to make up an answer.
    {context}
    Question: {question}
"""

custom_rag_prompt = PromptTemplate.from_template(template)

# This function will take a list of Document objects and return a single string
def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

# Construct a chain to answer questions on your data
rag_chain = (
    # Step 1: Get the question and retrieve documents.
    # The output of this step will be {"question": ..., "context": [list of Document objects]}
    {"context": retriever, "question": RunnablePassthrough()}
    # Step 2: Debug the retrieved context (which are still Document objects here).
    # The output will remain {"question": ..., "context": [list of Document objects]}
    | RunnablePassthrough.assign(
        # Pass the current 'context' (list of Documents) to the debug function
        # The result of debug_chain_input isn't added to the main flow, it just prints.
        # So we use a lambda that returns the context, keeping the flow clean.
        debug_retrieved_context=RunnableLambda(lambda x: debug_chain_input({"context": x["context"], "question": x["question"]}))
    )
    # Step 3: Format the 'context' from list of Documents to a single string.
    # The input to this step is {"question": ..., "context": [list of Document objects]}.
    # The output of this step will be {"question": ..., "context": "formatted string"}
    | {"context": RunnableLambda(lambda x: format_docs(x["context"])),
       "question": RunnablePassthrough()}
    # Step 4: Apply the custom prompt template.
    # The input to this step is {"question": ..., "context": "formatted string"}.
    # The output of this step is a PromptValue object.
    | custom_rag_prompt
    # Step 5: Debug the final prompt sent to the LLM.
    | RunnableLambda(debug_prompt_output)
    # Step 6: Invoke the LLM.
    | model
    # Step 7: Parse the output.
    | StrOutputParser()
)

# Prompt the chain to answer a question
question = "Dime una enseñanza sobre la muerte"
answer = rag_chain.invoke(question)
print(answer)